# 定义docker-compose文件版本
version: '2.27.0'
# 定义服务
services:
  # 定义mysql服务
  mysql:
    # 使用mysql 5.7的镜像
    image: mysql:5.7
    # 容器名称为meet-friends-mysql
    container_name: meet-friends-mysql
    # 设置环境变量MYSQL_ROOT_PASSWORD为kjq
    environment:
      # LANG表示语言，解决添加数据库乱码问题
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: kjq
    # 将宿主机的3306端口映射到容器的3306端口
    ports:
      - "3306:3306"
    # 将mysql数据目录挂载到宿主机的./mysql/data目录
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d # 导入数据库脚本，启动容器时执行
    # 总是重新启动容器
    restart: always
    # 加入mynetwork网络
    networks:
      - mynetwork
  # 定义redis服务
  redis:
    # 使用redis的镜像
    image: redis:6
    # 容器名称为meet-friends-redis
    container_name: meet-friends-redis
    # 端口映射
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    # 持久化数据目录挂载
    volumes:
      - ./redis/data:/data
  # 定义minio服务
  # minio:
  #   # 使用minio的镜像
  #   image: minio/minio:RELEASE.2024-03-30T09-41-56Z
networks:
  mynetwork: