server:
  port: 8081
#  servlet:
#    context-path: /api
spring:
  # 配置默认环境
  profiles:
    active: dev
  # 项目名称
  application:
    name: meet-friends
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center
    username: root
    password: kjq
  mvc:
    pathmatch:
      # 只有配置他swagger才能正常使用
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间
  session:
    # session失效时间 单位/分钟。一天失效
    timeout: 1440
    # 让redis管理session
    store-type: redis
  # 配置redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 默认是0库，使用那个数据库
    database: 0
    # 连接超时时间
    timeout: 5000
    password: kjq
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 30MB
      # 文件上传和表单数据不能超过35mb
      max-request-size: 35MB

mybatis-plus:
  configuration:
    # 不支持驼峰命名
    map-underscore-to-camel-case: false
    # 开启打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# minio相关配置
minio:
  endpoint: http://localhost:9000 #Minio服务所在地址
  bucketName: meet-friends #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
